INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("clean beach", "environment", 500, "2018-05-05", "2018-05-07");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("tutor math", "education", 300, "2018-03-01", "2018-03-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("restore bridge", "community", 1500, "2018-06-01", "2018-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("read to seniors", "community", 250, "2018-07-01", "2018-07-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("fire safety", "education", 250, "2018-06-01", "2018-06-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("plant trees", "environment", 1800, "2018-04-20", "2018-04-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("letters to the troops", "community", 150, "2018-05-25", "2018-05-28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("upgrade library computers", "community", 10000, "2018-08-01", "2018-12-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("pickup litter", "environment", 500, "2018-03-28", "2018-03-29");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("CPR training", "education", 450, "2018-09-03", "2018-09-23");

INSERT INTO users (name, age) VALUES ("Sterling", 35);
INSERT INTO users (name, age) VALUES ("Mallory", 62);
INSERT INTO users (name, age) VALUES ("Lana", 33);
INSERT INTO users (name, age) VALUES ("Pam", 29);
INSERT INTO users (name, age) VALUES ("Carol", 23);
INSERT INTO users (name, age) VALUES ("George Michael", 38);
INSERT INTO users (name, age) VALUES ("Maebe", 15);
INSERT INTO users (name, age) VALUES ("Gob", 40);
INSERT INTO users (name, age) VALUES ("Buster", 30);
INSERT INTO users (name, age) VALUES ("Lindsay", 28);
INSERT INTO users (name, age) VALUES ("Daria", 17);
INSERT INTO users (name, age) VALUES ("Quinn", 15);
INSERT INTO users (name, age) VALUES ("Jane", 18);
INSERT INTO users (name, age) VALUES ("Trent", 21);
INSERT INTO users (name, age) VALUES ("Liz", 38);
INSERT INTO users (name, age) VALUES ("Tracy", 42);
INSERT INTO users (name, age) VALUES ("Thor", 75);
INSERT INTO users (name, age) VALUES ("Loki", 55);
INSERT INTO users (name, age) VALUES ("Remy", 32);
INSERT INTO users (name, age) VALUES ("Scott", 42);


INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 9, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 13, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 16, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 18, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 11, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 15, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 18, 8);